### ISSUE TITLE
[Question] What is this code licensed under?

### ISSUE THREAD

**Issue by PatrickBauer** [BoltsJ/lancer-initiative#11]
Hey @BoltsJ,
I love this popcorn implementation and would like to integrate this module (or parts of it) into my Fate system (https://github.com/anvil-vtt/FateX). Is that allowed? I'd mention this as a contribution in my code, readme and licensing text but you don't provide any licensing information right now 😁

**Comment by BoltsJ** [comment]
I plan on eventually releasing this as an npm module, but `foundry-vtt-types` is a bit too volatile at the moment. I will have a license by that time. Probably in time for Foundry 0.8.x beta releases.

**Comment by BoltsJ** [comment]
Closed by 6886748bad3c18f12bf7dcb10b7c177db291e0eb
