### ISSUE TITLE
Unable to launch combat with 0.86

### ISSUE THREAD

**Issue by kunxin-chor** [BoltsJ/lancer-initiative#15]
<details>
<summary>Basic information</summary>

 - Lancer Initiative version: 0.5
 - Foundry VTT version: 0.86
 - Game system and version: D&D 5E
 - List of modules related to the combat tracker:  None

</details>

### Description of the issue

Unable to launch combat encounter (used to work with v0.79 even with the D&D 5E system)

**To Reproduce**
1. Select tokens
2. Right click to toggle combat state
3. Lancer Initiative is not launched

**Expected behavior**
Lancer combat initiative to launch 

**Console output**

![image](https://user-images.githubusercontent.com/14900791/120542828-25f7ec80-c41e-11eb-9dd1-e3d7ef212de8.png)

**Comment by BoltsJ** [comment]
0.8.6 isn't supported yet
