### ISSUE TITLE
Can't toggle visibility of actors on the combat tracker

### ISSUE THREAD

**Issue by Alkyama** [BoltsJ/lancer-initiative#18]
<details>
<summary>Basic information</summary>

 - Lancer Initiative version: 0.6.1
 - Foundry VTT version: 0.8.7
 - Game system and version: Lancer 0.9.4
 - List of modules related to the combat tracker: Disabled every module except for Lancer Initiative for debugging purposes.

</details>

### Description of the issue
Clicking on the _toggle visibility_ action on the combat tracker makes the actor vanish instantly, even for the GM. However the token is supposedly still in the combat tracker, as seen on the contextual menu from the token.

**To Reproduce**
1. Add an actor to the Combat Tracker (Did this with an NPC)
2. Click on 'toggle visibility'
4. See error (actor vanishes from combat tracker)

**Expected behavior**
Character was supposed to still be visible to the GM with indication that it's hidden to the players, so I could toggle it's visibility again or let them have their activations correctly set up.

**Console output**
No errors were found in the console.

**Screenshots**
![image](https://user-images.githubusercontent.com/25304929/123515411-a69cb800-d66d-11eb-9dff-6b8a6806d992.png)
![image](https://user-images.githubusercontent.com/25304929/123515426-b61c0100-d66d-11eb-8279-cad5c20e6b47.png)

**Additional context**
N/A

**Additional contact info**
alkyama#2737 on Discord.

**Comment by BoltsJ** [comment]
This is a bug in the lancer system CSS and there's not much I can do about it. It should be fixed in the next version of the system, but in the mean time, you can fix it by editing `systems/lancer/lancer.css` and removing the following lines (lines1935-1937)
```css
.hidden {
  display: none;
}
```
I hope that helps.
