### ISSUE TITLE
BUG: New Combats start with "Unknown Combatant"

### ISSUE THREAD

**Issue by EsotericOdyssey** [BoltsJ/lancer-initiative#21]
<details>
<summary>Basic information</summary>

 - Lancer Initiative version: v22
 - Foundry VTT version: V9
 - Game system and version: Simple Worldbuilding 0.6.2
 - List of modules related to the combat tracker: Lancer Initiative

</details>

### Description of the issue
Whenever I create a combat encounter, it generates a hidden combatant, simply named "Unknown Combatant", in the tracker, even if there are no tokens on the canvas, no scene in the world for there to even have a canvas present, or no actors in the world.

**To Reproduce**
1. Run Foundry VTT V9 with Simple Worldbuilding version 0.6.2, with Lancer Initiative module v22 enabled
2. Click on the Combat Tracker tab
3. use the '+' button to create a combat encounter

**Expected behavior**
I would've expected the combat encounter to begin empty, with no combatants tracked, as it does when Lancer Initiative is not enabled, regardless of any other combat-tracker-related modules that are or are not enabled.

**Console output**
No errors, and no specific message noting the creation of the Unknown Combatant.

**Additional context**
Intended to use Lancer Initiative for a game other than Lancer, in conjunction with the Simultaneous Combat System module in the Simple Worldbuilding System, as the two put together serve as a best-fit for the way initiative works in the game I wish to run.

**Additional contact info**
EsotericOdyssey#9387 on Discord

**Comment by EsotericOdyssey** [comment]
UPDATE: Errational on the FVTT discord says the Unknown Combatant is a dummy combatant that was present in previous versions, just not visible until V9 changed something or other, and that its presence was necessary to making the combat tracker work with Lancer Initiative. I've deleted the dummy combatant and I seem to be able to use up combatants' activations and advance rounds, go back in rounds, and everything else without the dummy combatant present. Are you sure it's still necessary?

**Comment by EsotericOdyssey** [comment]
UPDATE 2: Apparently the core combat tracker can now have turns set to ``null``, it appears as though this is no longer, in fact, necessary

**Comment by BoltsJ** [comment]
This is an issue with foundry v9. I have it fixed in the repository, but I don't have a computer right now so I can't cut a new release.

**Comment by EsotericOdyssey** [comment]
RIP
