### ISSUE TITLE
Consider making this module compatible with token markers

### ISSUE THREAD

**Issue by DarKDinDoN** [BoltsJ/lancer-initiative#24]
**Is your feature request related to a problem? Please describe.**
This module is awesome thx!

Some modules are displaying markers below tokens that have their turn in the combat tracker. For example:
- "Add turn marker" for the module: https://github.com/kandashi/Next-Up
- "Token combat highlight" for the module: https://github.com/ironmonk88/monks-little-details

![image](https://user-images.githubusercontent.com/1687854/158299889-e59ee142-204c-4969-86e6-4816ab59cc17.png)

**Describe the solution you'd like**
The issue is that this module doesn't seem to be compatible with those features.
- Next up: the marker is shown, but not for the first combatant of the round
- Monk's little details: no marker shown

Do you think there is a way to make this compatible?

**Comment by BoltsJ** [comment]
This is a problem with those modules. Combat booster is compatible, though.
