### ISSUE TITLE
[V10] When module is enabled, the Combat Tracker layout is messed up

### ISSUE THREAD

**Issue by r-valyar** [BoltsJ/lancer-initiative#26]
<details>
<summary>Basic information</summary>

 - Lancer Initiative version: 24 (this is what I see in the module enable/disable dialog)
 - ![image](https://user-images.githubusercontent.com/63558984/187841725-38e50b03-cf4d-43bf-b2f8-1dfbfc704545.png)
 - Foundry VTT version: 10.283
 - Game system and version: Conan 1.7.1
 - List of modules related to the combat tracker: no other module is loaded

</details>

### Description of the issue

When the module is enabled, the GUI of combat tracker is messed up and shows empty space.

**To Reproduce**
Enable the module. 

**Expected behavior**
No empty box in the combat tracker

**Console output**

```
Error: You are accessing the LancerCombat#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    logCompatibilityWarning https://foundry.bluealley.net/scripts/commons.js:1239
    _logV10CompatibilityWarning https://foundry.bluealley.net/scripts/commons.js:6143
    get data https://foundry.bluealley.net/scripts/commons.js:6043
    lookupProperty https://foundry.bluealley.net/scripts/handlebars.min.js:27
    anonymous https://foundry.bluealley.net/scripts/handlebars.min.js line 29 > Function:10
    h https://foundry.bluealley.net/scripts/handlebars.min.js:27
    default https://foundry.bluealley.net/scripts/handlebars.min.js:27
    c https://foundry.bluealley.net/scripts/handlebars.min.js:27
    anonymous https://foundry.bluealley.net/scripts/handlebars.min.js line 29 > Function:15
    c https://foundry.bluealley.net/scripts/handlebars.min.js:27
    d https://foundry.bluealley.net/scripts/handlebars.min.js:27
    e https://foundry.bluealley.net/scripts/handlebars.min.js:28
    renderTemplate https://foundry.bluealley.net/scripts/foundry.js:6813
[commons.js:1250:34](https://foundry.bluealley.net/scripts/commons.js)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/63558984/187841259-8afba9d7-60f1-464f-9d4f-e61add00fa44.png)

**Additional context**
n/a

**Additional contact info**
n/a

**Comment by BoltsJ** [comment]
This module isn't compatible with v10 at this time

**Comment by r-valyar** [comment]
@BoltsJ is there plan to make it compatible? It is clear that is it not working with v10, as I reported the bug :)

**Comment by BoltsJ** [comment]
I do plan to make this v10 compatible, but I don't know exactly when I'll have time. I recommend staying on v9 if this module is essential to your game.

**Comment by r-valyar** [comment]
I am afraid I can't stay on v9, due to major system changes that my group needs (fixes a lot of issues) and I had to migrate. 
I hope you will manage to find time and update the module in near future, it is excellent extension.
