### ISSUE TITLE
Initiative Icon changes for players

### ISSUE THREAD

**Issue by superseva** [BoltsJ/lancer-initiative#34]
The action icon doesn't change when players look at the initiative tracker.
It would be helpful if the icon for combatant's action would also change in color (grayed out) once the combatant spend his actions in the players' initiative tracker.

**Comment by superseva** [comment]
oh sorry it does that, but sometimes it doesn't :) let me log that as bug then maybe ?

**Comment by BoltsJ** [comment]
If the icon isn't changing to grey, then it's a bug, but I will need you to fill out the template or I won't be able to troubleshoot it.
