### ISSUE TITLE
[Bug] Right click Popped out Combat tracker activation icons do not match icons shown in right-side panel combat tracker.

### ISSUE THREAD

**Issue by Dom-Odyssey** [BoltsJ/lancer-initiative#35]
<details>
<summary>Basic information</summary>

 - Lancer Initiative version: 26
 - Foundry VTT version: 10.290
 - Game system and version: DnD5e 2.0.3
 - List of modules related to the combat tracker: None

</details>

### Description of the issue

When the combat tracker is popped out by right clicking the combat tracker icon on the right-side panel tab the lancer activation icons all appear to be small grey and not representative of the icons shown in the actual tab on the right-side panel.

**To Reproduce**
1. create an encounter with actors
2. Right click on the combat tracker icon
3. look at the popped-out combat tracker window
4. See that the lancer activation icons are not the same as shown in the combat tracker

**Expected behavior**
The lancer activation icons in the popped-out combat tracker should match what the combat tracker on the right-side panel looks like 

**Console output**

Are there any errors printed to the console (F12) when the issue occurs? 
No

**Screenshots**
![image](https://user-images.githubusercontent.com/83840613/204684009-cfe954e8-f8d5-4ed7-92ce-bf21f69bf439.png)

**Additional context**

**Additional contact info**

Discord username, email, or other places that you're okay with getting contacted for more information. **This is optional.**

**Comment by PatrickBauer** [comment]
I can confirm this. Not seeing the activation states inside the popped out window isn't great right now.

**Comment by BoltsJ** [comment]
Should be fixed in v27.
