### ISSUE TITLE
Next Round triggers AE "Start of next turn" duration

### ISSUE THREAD

**Issue by VladGrant** [BoltsJ/lancer-initiative#36]
<details>
<summary>Turn Start for target duration triggered on new round</summary>

 - Lancer Initiative version: (v26)
 - Foundry VTT version: (ex 10.291)
 - Game system and version: (ex. dnd5e 2.1.4)
</details>

### Description of the issue

I have an effect whose duration is Turn Start, however the moment I move to a new round the effect disappears, not when the token is activated. I'm sure this has to do with changing the turn to null, but I did not see this in the known issues 
**To Reproduce**
1. Create an Active Effect with duration set to " Turn Start: expires at start of target's next turn (in combat)"
2. Start combat with a couple actors
3. Apply the effect from step 1 to one of them during their turn
4. Activate the other actor
5. Move to the next round
6. The effect on the first actor from step 3 expires without being activate.

**Expected behavior**
Effects expire as actors are activated instead of start of round.

**Console output**

```
foundry.js:49 
        
       TypeError: Error thrown in hooked function '_updateCombat' for hook 'updateCombat'. Cannot read properties of undefined (reading 'token')
[Detected 1 package: dnd5e-helpers]
    at Object._updateCombat [as fn] (Regeneration.js:4:247)
    at #call (foundry.js:48:97)
    at Hooks.callAll (foundry.js:43:101)
    at ClientDatabaseBackend.callback (foundry.js:797:202)
    at foundry.js:794:332
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:794:324)
    at ClientDatabaseBackend._updateDocuments (foundry.js:781:442)
    at async LancerCombat.updateDocuments (commons.js:415:162)
    at async LancerCombat.update (commons.js:418:115)
    at async MonksCombatTracker._onCombatControl (foundry.js:7139:234)
onError @ foundry.js:49
🎁call_wrapped @ lib-wrapper.js:1
🎁Hooks.onError#lib-wrapper @ lib-wrapper.js:1
🎁Hooks.onError#0 @ lib-wrapper.js:1
#call @ foundry.js:48
callAll @ foundry.js:43
callback @ foundry.js:797
(anonymous) @ foundry.js:794
_handleUpdateDocuments @ foundry.js:794
_updateDocuments @ foundry.js:781
await in _updateDocuments (async)
update @ commons.js:462
await in update (async)
updateDocuments @ commons.js:415
update @ commons.js:418
nextRound @ lancer-initiative.js:1
await in nextRound (async)
_onCombatControl @ foundry.js:7139
(anonymous) @ foundry.js:7136
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

**Additional context**
I realize this might not be something that can be fixed, but I didn't see it in the known issues list.

**Additional contact info**

Discord username, email, or other places that you're okay with getting contacted for more information. **This is optional.**

**Comment by BoltsJ** [comment]
Sorry, I forgot to send this message earlier. I can't look into this at all if you don't provide the requested info, but also this is almost certainly a problem with core foundry, since a lot of the combat and active effect logic is hardcoded to work exactly like dnd5e does is and the farther you get away from it, the more broken it gets. I do what I can where I can, but in the case of active effect duration, this is soundly a problem that will have to be fixed either in core foundry, or possibly your system.
