### ISSUE TITLE
Attempting to roll Initiative from a character sheet adds the actor, but fails to roll.

### ISSUE THREAD

**Issue by hollowman123** [BoltsJ/lancer-initiative#8]
feature request for if a player clicks on initiative in their character sheet it outputs a standard initiative roll into the chat. this would be useful for DMs who use popcorn initiative and use initiative rolls to determine which side/player acts first for encounters.

**Comment by BoltsJ** [comment]
To clarify, are you wanting a way for players to roll initiative from the combat tracker?

**Comment by BoltsJ** [comment]
I've added a fix that allows the roll all button to work. I'm looking into a way to add a button to roll to the combatant controls for the players.

**Comment by hollowman123** [comment]
> To clarify, are you wanting a way for players to roll initiative from the combat tracker?

With the base game when the initiative font is clicked from the character sheet it outputs a chat message and rolls the player into the combat tracker. I was thinking just the message would be easiest to implement but the combat tracker would be better.

**Comment by BoltsJ** [comment]
There's a bug in the way foundry handles the actual steps to adding and fails to properly check for null values, causing the function to raise an exception and bail out before initiative is rolled, but after the combatant is added to the tracker.

**Comment by BoltsJ** [comment]
[0.4.3](https://github.com/BoltsJ/lancer-initiative/releases/tag/0.4.3) adds a button on the combat tracker to roll.

**Comment by VladGrant** [comment]
If this a bug in foundry core, have you by any chance opened a bug report against it? I just ran into the bug, which I am guessing is what throws the following error:
```
TypeError: c.actor is null
```
If you did open an issue could you post it here so we could all follow it?

**Comment by BoltsJ** [comment]
I reported it here: https://gitlab.com/foundrynet/foundryvtt/-/issues/2042#note_471727674

**Comment by BoltsJ** [comment]
This has has been resolved in the 0.8.x updates and will be fully working when I release 0.6 of this module.
